//! Memory tools (store, recall, forget)
//!
//! Provides long-term memory for Agents via the [`MemoryStore`] trait.

use atta_memory::traits::{MemoryEntry, MemoryMetadata, SearchOptions};
use atta_types::{AttaError, MemoryType, RiskLevel};
use serde_json::{json, Value};
use uuid::Uuid;

use crate::MemoryStoreRef;

/// Store a memory entry
pub struct MemoryStoreTool {
    pub store: MemoryStoreRef,
}

impl MemoryStoreTool {
    /// Create with optional memory store reference
    pub fn new(store: MemoryStoreRef) -> Self {
        Self { store }
    }
}

#[async_trait::async_trait]
impl atta_types::NativeTool for MemoryStoreTool {
    fn name(&self) -> &str {
        "atta-memory-store"
    }

    fn description(&self) -> &str {
        "Store information in long-term memory for later recall"
    }

    fn risk_level(&self) -> RiskLevel {
        RiskLevel::Low
    }

    fn parameters_schema(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "description": "Content to store in memory"
                },
                "tags": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Tags for categorization"
                },
                "memory_type": {
                    "type": "string",
                    "enum": ["knowledge", "episodic", "procedural", "semantic"],
                    "description": "Type of memory (default: knowledge)"
                }
            },
            "required": ["content"]
        })
    }

    async fn execute(&self, args: Value) -> Result<Value, AttaError> {
        let Some(store) = &self.store else {
            return Err(AttaError::Validation(
                "MemoryStore not available".to_string(),
            ));
        };

        let content = args["content"]
            .as_str()
            .ok_or_else(|| AttaError::Validation("'content' is required".into()))?;

        let tags: Vec<String> = args["tags"]
            .as_array()
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();

        let memory_type = args["memory_type"]
            .as_str()
            .and_then(|s| serde_json::from_str(&format!("\"{s}\"")).ok())
            .unwrap_or(MemoryType::Knowledge);

        let id = Uuid::new_v4();
        let now = chrono::Utc::now();

        let entry = MemoryEntry {
            id,
            memory_type,
            content: content.to_string(),
            embedding: None, // auto-generated by store
            metadata: MemoryMetadata {
                tags,
                ..Default::default()
            },
            created_at: now,
            last_accessed: now,
            access_count: 0,
        };

        store.store(entry).await?;

        Ok(json!({
            "status": "stored",
            "id": id.to_string(),
        }))
    }
}

/// Recall information from long-term memory
pub struct MemoryRecallTool {
    pub store: MemoryStoreRef,
}

impl MemoryRecallTool {
    /// Create with optional memory store reference
    pub fn new(store: MemoryStoreRef) -> Self {
        Self { store }
    }
}

#[async_trait::async_trait]
impl atta_types::NativeTool for MemoryRecallTool {
    fn name(&self) -> &str {
        "atta-memory-recall"
    }

    fn description(&self) -> &str {
        "Recall information from long-term memory by semantic search"
    }

    fn risk_level(&self) -> RiskLevel {
        RiskLevel::Low
    }

    fn parameters_schema(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Search query (semantic or keyword)"
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum results (default: 5)",
                    "default": 5
                },
                "memory_types": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Filter by memory type"
                }
            },
            "required": ["query"]
        })
    }

    async fn execute(&self, args: Value) -> Result<Value, AttaError> {
        let Some(store) = &self.store else {
            return Err(AttaError::Validation(
                "MemoryStore not available".to_string(),
            ));
        };

        let query = args["query"]
            .as_str()
            .ok_or_else(|| AttaError::Validation("'query' is required".into()))?;

        let limit = args["limit"].as_u64().unwrap_or(5) as usize;

        let memory_types: Option<Vec<MemoryType>> = args["memory_types"].as_array().map(|arr| {
            arr.iter()
                .filter_map(|v| {
                    v.as_str()
                        .and_then(|s| serde_json::from_str(&format!("\"{s}\"")).ok())
                })
                .collect()
        });

        let options = SearchOptions {
            limit,
            memory_types,
            ..Default::default()
        };

        let results = store.search(query, &options).await?;

        let items: Vec<Value> = results
            .iter()
            .map(|r| {
                json!({
                    "id": r.entry.id.to_string(),
                    "content": r.entry.content,
                    "score": r.score,
                    "match_source": format!("{:?}", r.match_source),
                    "memory_type": r.entry.memory_type,
                    "tags": r.entry.metadata.tags,
                    "created_at": r.entry.created_at.to_rfc3339(),
                })
            })
            .collect();

        Ok(json!({
            "status": "ok",
            "count": items.len(),
            "results": items,
        }))
    }
}

/// Delete a memory entry by ID
pub struct MemoryForgetTool {
    pub store: MemoryStoreRef,
}

impl MemoryForgetTool {
    /// Create with optional memory store reference
    pub fn new(store: MemoryStoreRef) -> Self {
        Self { store }
    }
}

#[async_trait::async_trait]
impl atta_types::NativeTool for MemoryForgetTool {
    fn name(&self) -> &str {
        "atta-memory-forget"
    }

    fn description(&self) -> &str {
        "Delete a memory entry by ID"
    }

    fn risk_level(&self) -> RiskLevel {
        RiskLevel::Low
    }

    fn parameters_schema(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Memory entry UUID to delete"
                }
            },
            "required": ["id"]
        })
    }

    async fn execute(&self, args: Value) -> Result<Value, AttaError> {
        let Some(store) = &self.store else {
            return Err(AttaError::Validation(
                "MemoryStore not available".to_string(),
            ));
        };

        let id_str = args["id"]
            .as_str()
            .ok_or_else(|| AttaError::Validation("'id' is required".into()))?;

        let id = Uuid::parse_str(id_str)
            .map_err(|e| AttaError::Validation(format!("invalid UUID: {e}")))?;

        store.delete(&id).await?;

        Ok(json!({
            "status": "deleted",
            "id": id_str,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use atta_types::NativeTool;

    #[test]
    fn test_memory_tool_names() {
        assert_eq!(MemoryStoreTool::new(None).name(), "atta-memory-store");
        assert_eq!(MemoryRecallTool::new(None).name(), "atta-memory-recall");
        assert_eq!(MemoryForgetTool::new(None).name(), "atta-memory-forget");
    }

    #[tokio::test]
    async fn test_memory_store_without_store() {
        let tool = MemoryStoreTool::new(None);
        let result = tool.execute(json!({"content": "hello"})).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_memory_recall_without_store() {
        let tool = MemoryRecallTool::new(None);
        let result = tool.execute(json!({"query": "hello"})).await;
        assert!(result.is_err());
    }
}
